server:
  port: 8889
spring:
  elasticsearch:
    jest:
#      uris: ["http://192.168.43.210:9200", "http://192.168.176.128:9200"]
      uris: http://192.168.176.128:9200
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.176.128:9300

elasticsearch:
  cluster:
    name: elasticsearch
  ip: 192.168.176.128
  port: 9300
